## Build the Environment

FROM node:14.19.0-alpine as build
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

COPY . ./

RUN npm run build


## Production Environment

FROM nginx:stable-alpine
WORKDIR /var/www/jenssens

COPY --from=build /usr/src/app/build /var/www/jenssens
COPY /deploy_dev/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]